### ISSUE TITLE
Portrait mode -> landscape mode bug

### ISSUE THREAD

**Issue by PyThrrrone** [PyThrrrone/ScreenSlaver#1]
1. Start the script in portrait mode.
2. Turn the IPad to landscape mode.
3. Result: The used canvas is no longer the complete display. Only 2/3 of it.

Anyone with an idea, how to solve that?
![FAA9374F-415F-41F5-9676-210E380CF62B](https://user-images.githubusercontent.com/96354848/147156620-72068770-90e8-4592-a0d2-30644f39b920.png)

**Comment by pome-ta** [comment]
[https://github.com/pome-ta/ScreenSlaver/commit/1d7709e03b251def692e85614a1e0eda620e5176](https://github.com/pome-ta/ScreenSlaver/commit/1d7709e03b251def692e85614a1e0eda620e5176)

```
def did_change_size(self):
      self.sprite.size = ui.get_screen_size()
      self.sprite.position = self.size/2
```


Does this process solve your wishes?
